name: slicer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - gcc_linux-64
  - gxx_linux-64
  - _libgcc_mutex
  - _openmp_mutex
  - bzip2
  - ca-certificates
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libstdcxx-ng
  - libuuid
  - multipledispatch
  - ncurses
  - openssl
  - pip
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pip:
    - --extra-index-url https://download.blender.org/pypi/
    - bpy==3.4.0
    - addict
    - asttokens
    - attrs
    - autoprop
    - blender-plots
    - blinker
    - certifi
    - chardet
    - charset-normalizer
    - click
    - colorlog
    - comm
    - configargparse
    - contourpy
    - cycler
    - cython
    - dash
    - dash-core-components
    - dash-html-components
    - dash-table
    - decorator
    - exceptiongroup
    - executing
    - fastjsonschema
    - flask
    - fonttools
    - freetype-py
    - glooey
    - heart
    - hnswlib
    - idna
    - imageio
    - importlib-metadata
    - ipython
    - ipywidgets
    - itsdangerous
    - jedi
    - jinja2
    - joblib
    - jsonschema
    - jsonschema-specifications
    - jupyter-core
    - jupyterlab-widgets
    - kiwisolver
    - lazy-loader
    - llvmlite
    - lxml
    - mapbox-earcut
    - markdown-it-py
    - markupsafe
    - matplotlib
    - matplotlib-inline
    - mdurl
    - mesh-to-sdf
    - meshio
    - more-itertools
    - mpmath
    - narwhals
    - nbformat
    - nest-asyncio
    - networkx
    - numba
    - numexpr
    - numpy
    - open3d
    - opencv-python
    - packaging
    - pandas
    - parso
    - pexpect
    - pillow
    - platformdirs
    - plotly
    - pooch
    - prompt-toolkit
    - psutil
    - ptyprocess
    - pure-eval
    - pycollada
    - pyglet
    - pygments
    - pymeshfix
    - pyopengl
    - pyparsing
    - pyquaternion
    - pyrender
    - python-dateutil
    - python-fcl
    - pytz
    - pyvista
    - pyyaml
    - referencing
    - requests
    - retrying
    - rich
    - rpds-py
    - rtree
    - scikit-image
    - scikit-learn
    - scipy
    - scooby
    - shapely
    - signature-dispatch
    - simsimd
    - six
    - stack-data
    - svg-path
    - svv
    - sympy
    - tetgen
    - threadpoolctl
    - tifffile
    - tqdm
    - traitlets
    - trimesh
    - typeguard
    - typing-extensions
    - tzdata
    - urllib3
    - usearch
    - vecrec
    - vtk
    - wcwidth
    - werkzeug
    - widgetsnbextension
    - xatlas
    - xxhash
    - zipp
    - zstandard
