[project]
name = "slicer"
version = "0.0.1"
authors = [
  { name="Gadiel Sznaier Camps", email="gsznaier@stanford.edu" },
]
description = "Universal Multiplayer SWARM Slicer: A slicer for multi-axis, multi-CTR printing."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/gsznaier/Universal-Multiplayer-SWARM-Slicer"
Issues = "https://github.com/gsznaier/Universal-Multiplayer-SWARM-Slicer/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

